[package]
edition = "2021"
name = "adminix"
version = "0.0.1"

[dependencies.adminix_macro]
package = "adminix_macro"
path = "adminix_macro"
version = "0.0.1"


[workspace]

members = [
    "adminix_macro",
    "adminix_tests",
]